#line 2 "lex.yy.cc"

#line 4 "lex.yy.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int yylineno;
int yylineno = 1;

extern char yytext[];

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( yytext, (yytext_ptr), yyleng + 1 ); \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 22
#define YY_END_OF_BUFFER 23
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[157] =
    {   0,
        0,    0,   23,   21,    2,    1,   21,   21,    6,   21,
        4,    3,   14,   21,   21,    5,   20,   21,   21,   14,
       21,    0,   11,   21,   14,   21,   21,    7,    9,    8,
       14,   14,   14,   14,   21,    0,   21,   14,   12,   21,
       20,   20,   20,   14,   11,   11,   14,   11,   14,   14,
       14,   21,    0,   21,   12,   14,   21,    0,   21,   21,
       21,   21,   14,   21,   19,   10,   12,   12,   14,   14,
       14,   14,   12,   21,   14,   14,   14,   14,   11,   11,
       12,   12,   14,   14,   12,   14,   14,   19,   17,   15,
       19,   16,   14,   14,   14,   14,   14,   18,   19,   19,

       19,   19,   14,   12,   12,   21,   12,   12,   19,   19,
       14,   14,   14,   14,   14,   14,   14,   19,   21,   19,
       19,   14,   14,   14,   19,   19,   19,   19,   14,   19,
       21,   19,   19,   19,   19,   14,   14,   14,   14,   14,
       14,   14,   14,   19,    0,   19,   19,   14,   14,   14,
       14,   14,   13,   14,   14,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    7,    1,    8,    1,    9,
       10,    1,    1,    1,    1,    1,    1,    1,    1,   11,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   12,
        1,   13,   14,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   15,    1,    1,   16,   17,    1,    1,   18,    1,

       19,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       20,    1,    1,   21,   22,    1,   23,    1,    1,    1,
        1,    1,   24,   25,   26,   27,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[28] =
    {   0,
        1,    2,    3,    4,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    6,    1,    1
    } ;

static const flex_int16_t yy_base[204] =
    {   0,
        0,    0,  217,   20, 1358, 1358,   34,   52,    0,   20,
        0,   26,   69,   93,   21, 1358,  111,   28,    0,  129,
      153,  206,   34,  177,  201,  225,  250, 1358, 1358,  203,
        0,   37,    0,    0,  276,  191,  300,  324,   39,   42,
      342,   43,    0,  360, 1358,    0,  384,    0,  408,   51,
        0,  432,  194,  456,    0,  480,   64,  172,  501,  162,
       73,  160,  526,  158,  551, 1358, 1358,    0,  575,  599,
       68,    0,    0,   79,  617,   66,    0,    0,   77,    0,
      153,  641,  665,  689,    0,  105,    0,  146,  713,    0,
      109,    0,  737,  125,   87,    0,  762,    0,    0,  142,

      124,  118,  786,   79,    0,  121,  810,  154,  105,  834,
      160,  126,    0,  122,  167,  133,    0,  858,  151,   47,
      883,  908,  169,  932,  957,   67,  108,  982, 1007,    0,
      173,  165,  114,   93,   90, 1032,  192,    0,   72, 1057,
      193,    0,    0,    0,    0,  180,    0,   63,   59,  208,
      145,    0,    0,    0,  194, 1358, 1083, 1088, 1094, 1099,
     1105, 1111, 1117, 1123, 1129, 1135, 1141, 1147, 1153, 1159,
     1165, 1171, 1177, 1183, 1189, 1195, 1201, 1207, 1213, 1219,
     1225, 1231, 1237, 1243, 1249, 1255, 1261, 1267, 1273, 1279,
     1285, 1291, 1297, 1303, 1309, 1315, 1321, 1327, 1333, 1339,

     1345, 1351,   30
    } ;

static const flex_int16_t yy_def[204] =
    {   0,
      156,    1,  156,  157,  156,  156,  158,  157,  159,    8,
      159,  156,  160,  161,    8,  156,  162,    8,  159,  160,
      158,  163,    8,  164,  165,  166,  156,  156,  156,  156,
       20,  167,  168,   20,  161,  169,  170,  171,    8,    8,
      162,  172,  173,  174,  156,  159,  165,   20,  175,  176,
       47,  166,  177,  178,   52,  179,   27,  180,   27,   59,
      181,   59,  182,   59,  183,  156,  156,  159,  171,  184,
      185,   69,   20,    8,  174,  186,  187,   75,  167,  168,
      177,  178,  179,  188,   83,  189,   83,  190,  183,   89,
      191,   89,  182,  192,  193,   93,  194,   89,   89,  190,

       89,  191,  194,  167,  168,    8,  188,  189,  190,  191,
      195,  196,  103,  103,  195,  196,  103,  197,    8,  198,
      199,  195,  196,  200,  197,  198,  125,  199,  200,   89,
        8,  198,  190,  128,  110,  201,  202,  129,  129,  201,
      202,  129,  103,  125,  203,  198,  128,  140,  122,  202,
      196,  129,  203,  140,  202,    0,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,

      156,  156,  156
    } ;

static const flex_int16_t yy_nxt[1386] =
    {   0,
        4,    5,    6,    5,    4,    7,    8,    9,    4,    4,
       10,   11,   12,    4,   13,    4,   14,    4,    4,    4,
        4,   15,    4,    4,   16,    4,   17,   19,   18,   18,
      153,   19,   28,   29,   20,   22,   18,   22,   30,   23,
       40,   24,   18,   18,   18,   24,   22,   18,   25,   33,
       18,   18,   22,  132,   22,   43,   80,   18,   22,   19,
       26,   33,   18,   19,   74,   18,   20,   43,   57,   36,
       57,   36,  133,  132,   58,   27,   32,   57,   77,   57,
       32,   33,  115,   34,  105,   58,  154,   18,   58,   33,
       77,   33,  133,   33,   36,  152,   36,   58,   91,  106,

       37,   33,   18,   33,   37,   36,   53,   38,   53,   39,
      100,  109,  112,  102,  108,  110,  147,   36,   42,  100,
      109,  100,   42,   43,  110,   44,   58,  100,  120,   18,
      100,  144,  123,  100,  100,   43,   32,   95,  119,  123,
       32,   33,  100,   34,   18,  124,  100,  118,  109,   95,
      111,  123,  109,   33,   22,   53,   22,   53,   23,   18,
       24,  100,   81,  108,   24,   22,  122,   25,  100,  131,
      100,  132,  116,  122,   18,  123,  145,   22,   22,  116,
       22,   18,   46,   98,  116,   92,  132,   90,  146,   22,
      133,  116,  137,  126,  126,  126,   18,   88,  150,  150,

      150,   22,   22,   81,   22,  133,   48,   67,   49,  126,
       66,   45,   49,   50,  150,   51,  156,  151,  151,  151,
      156,  156,  156,  156,  156,   50,   53,  156,   53,  156,
      156,  155,   54,  151,   55,  156,   54,   53,  156,   56,
      156,  156,  156,  156,  156,  156,  156,  156,  156,   53,
       57,   58,  156,  156,   59,   57,   60,   61,   57,   57,
       57,   61,   58,   62,   63,   64,   57,   57,   57,   57,
       57,   57,   57,   57,   58,   65,   57,   36,  156,   36,
      156,  156,  156,   37,  156,  156,  156,   37,   36,  156,
       38,  156,   39,  156,  156,  156,  156,  156,  156,  156,

       36,   36,  156,   36,  156,  156,  156,  156,  156,  156,
      156,  156,   36,  156,  156,  156,   68,  156,  156,  156,
      156,  156,  156,  156,   36,   36,  156,   36,  156,  156,
      156,   70,  156,  156,  156,   70,   71,  156,   72,  156,
       73,  156,  156,  156,  156,  156,  156,  156,   71,   42,
      156,  156,  156,   42,   43,  156,   44,  156,  156,  156,
      156,  156,  156,  156,  156,  156,   43,   76,  156,  156,
      156,   76,   77,  156,   78,  156,  156,  156,  156,  156,
      156,  156,  156,  156,   77,   22,  156,   22,  156,   48,
      156,   49,  156,  156,  156,   49,   50,  156,   51,  156,

      156,  156,  156,  156,  156,  156,  156,  156,   50,   22,
      156,   22,  156,   79,  156,  156,  156,  156,  156,  156,
       50,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,   50,   53,  156,   53,  156,  156,  156,   54,
      156,   55,  156,   54,   53,  156,   56,  156,  156,  156,
      156,  156,  156,  156,  156,  156,   53,   53,  156,   53,
      156,  156,  156,  156,  156,   82,  156,  156,   53,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
       53,   53,  156,   53,  156,  156,  156,   84,  156,   85,
      156,   84,   86,  156,   87,  156,  156,  156,  156,  156,

      156,  156,  156,  156,   86,   57,  156,   57,  156,  156,
      156,  156,  156,  156,   57,  156,   57,  156,  156,  156,
      156,  156,  156,  156,  156,  156,   89,   58,  156,  156,
      156,  156,  156,   94,  156,  156,  156,   94,   95,  156,
       96,  156,  156,  156,  156,  156,  156,  156,  156,  156,
       95,   97,  100,  156,  156,  156,  156,  101,  102,  156,
      156,  156,  102,  100,  156,  103,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  100,   36,  156,   36,  156,
      156,  156,   70,  156,  156,  156,   70,   71,  156,   72,
      156,   73,  156,  156,  156,  156,  156,  156,  156,   71,

       36,  156,   36,  156,  156,  156,  156,  156,  156,  156,
      156,   71,  156,  156,  156,  104,  156,  156,  156,  156,
      156,  156,  156,   71,   76,  156,  156,  156,   76,   77,
      156,   78,  156,  156,  156,  156,  156,  156,  156,  156,
      156,   77,   53,  156,   53,  156,  156,  156,  156,  156,
       82,  156,  156,   53,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,   53,   53,  156,   53,  156,
      156,  156,   84,  156,   85,  156,   84,   86,  156,   87,
      156,  156,  156,  156,  156,  156,  156,  156,  156,   86,
       53,  156,   53,  156,  156,  156,  156,  156,  107,  156,

      156,   86,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,   86,  100,  156,  156,  156,  156,  101,
      102,  156,  156,  156,  102,  100,  156,  103,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  100,   58,  156,
      156,  156,  156,  156,   94,  156,  156,  156,   94,   95,
      156,   96,  156,  156,  156,  156,  156,  156,  156,  156,
      156,   95,   97,  100,  156,  156,  156,  156,  114,  115,
      156,  156,  156,  115,  116,  156,  117,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  116,  100,  156,  156,
      156,  156,  114,  115,  156,  156,  156,  115,  116,  156,

      117,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      116,   53,  156,   53,  156,  156,  156,  156,  156,  107,
      156,  156,   86,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,   86,  100,  156,  156,  156,  156,
      110,  156,  156,  156,  156,  156,  100,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  121,  100,  126,
      156,  156,  156,  156,  127,  128,  156,  156,  156,  128,
      126,  156,  129,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  126,  130,  126,  156,  156,  156,  156,  134,
      156,  156,  156,  156,  156,  126,  156,  156,  156,  156,

      156,  156,  156,  156,  156,  156,  156,  126,  135,  100,
      156,  156,  156,  156,  122,  156,  156,  156,  156,  156,
      116,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  136,  116,  126,  156,  156,  156,  156,  139,  140,
      156,  156,  156,  140,  141,  156,  142,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  141,  143,  126,  156,
      156,  156,  156,  127,  128,  156,  156,  156,  128,  126,
      156,  129,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  126,  130,  126,  156,  156,  156,  156,  134,  156,
      156,  156,  156,  156,  126,  156,  156,  156,  156,  156,

      156,  156,  156,  156,  156,  156,  126,  135,  126,  156,
      156,  156,  156,  139,  140,  156,  156,  156,  140,  141,
      156,  142,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  141,  143,  126,  156,  156,  156,  156,  148,  156,
      156,  156,  156,  156,  141,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  141,  149,  126,  156,
      156,  156,  156,  148,  156,  156,  156,  156,  156,  141,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  141,  149,   18,  156,  156,  156,   18,   21,   21,
      156,   21,   21,   21,   19,  156,  156,  156,   19,   31,

      156,  156,  156,   31,   31,   35,   35,  156,   35,   35,
       35,   41,  156,  156,  156,   41,   41,   22,   22,  156,
       22,   22,   22,   24,   24,  156,   24,   24,   24,   47,
       47,  156,   47,   47,   47,   52,   52,  156,   52,   52,
       52,   32,  156,  156,  156,   32,   32,   33,  156,  156,
      156,   33,   33,   36,   36,  156,   36,   36,   36,   37,
       37,  156,   37,   37,   37,   69,   69,  156,   69,   69,
       69,   42,  156,  156,  156,   42,   42,   43,  156,  156,
      156,   43,   43,   75,  156,  156,  156,   75,   75,   49,
       49,  156,   49,   49,   49,   50,   50,  156,   50,   50,

       50,   53,   53,  156,   53,   53,   53,   54,   54,  156,
       54,   54,   54,   83,   83,  156,   83,   83,   83,   58,
       58,  156,  156,   58,   58,   61,   61,  156,  156,   61,
       61,   93,   93,  156,  156,   93,   93,   99,   99,  156,
      156,   99,   99,   70,   70,  156,   70,   70,   70,   71,
       71,  156,   71,   71,   71,   76,  156,  156,  156,   76,
       76,   77,  156,  156,  156,   77,   77,   84,   84,  156,
       84,   84,   84,   86,   86,  156,   86,   86,   86,  100,
      100,  156,  156,  100,  100,  102,  102,  156,  156,  102,
      102,   94,   94,  156,  156,   94,   94,   95,   95,  156,

      156,   95,   95,  113,  113,  156,  156,  113,  113,  115,
      115,  156,  156,  115,  115,  116,  116,  156,  156,  116,
      116,  125,  125,  156,  156,  125,  125,  126,  126,  156,
      156,  126,  126,  128,  128,  156,  156,  128,  128,  138,
      138,  156,  156,  138,  138,  140,  140,  156,  156,  140,
      140,  141,  141,  156,  156,  141,  141,    3,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156
    } ;

static const flex_int16_t yy_chk[1386] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    4,   10,   15,
      203,    4,   10,   12,    4,    7,   18,    7,   12,    7,
       15,    7,   23,   10,   15,    7,    7,   39,    7,   32,
       40,   18,   50,  120,   50,   42,   50,   23,    7,    8,
        8,   32,   39,    8,   40,   40,    8,   42,   57,   71,
       57,   71,  120,  126,   61,    8,   13,   57,   76,   57,
       13,   13,  149,   13,   71,   61,  148,   74,   95,   79,
       76,  104,  126,   13,   14,  139,   14,   61,   61,   74,

       14,   79,   74,  104,   14,   14,   86,   14,   86,   14,
       91,  109,   95,  135,   86,   91,  134,   14,   17,  102,
      133,   91,   17,   17,  102,   17,   94,  112,  109,  106,
      102,  127,  112,   91,  116,   17,   20,   94,  106,  116,
       20,   20,  102,   20,  106,  114,  151,  101,  100,   94,
       94,  151,   88,   20,   21,  108,   21,  108,   21,  119,
       21,  111,   81,  108,   21,   21,  111,   21,  115,  119,
      123,  132,  111,  115,  119,  123,  131,   21,   24,  115,
       24,  131,   24,   64,  111,   62,  146,   60,  132,   24,
      132,  115,  123,  137,  141,  155,  131,   58,  137,  141,

      155,   24,   25,   53,   25,  146,   25,   36,   25,  150,
       30,   22,   25,   25,  150,   25,    3,  137,  141,  155,
        0,    0,    0,    0,    0,   25,   26,    0,   26,    0,
        0,  150,   26,  150,   26,    0,   26,   26,    0,   26,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   26,
       27,   27,    0,    0,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   35,    0,   35,
        0,    0,    0,   35,    0,    0,    0,   35,   35,    0,
       35,    0,   35,    0,    0,    0,    0,    0,    0,    0,

       35,   37,    0,   37,    0,    0,    0,    0,    0,    0,
        0,    0,   37,    0,    0,    0,   37,    0,    0,    0,
        0,    0,    0,    0,   37,   38,    0,   38,    0,    0,
        0,   38,    0,    0,    0,   38,   38,    0,   38,    0,
       38,    0,    0,    0,    0,    0,    0,    0,   38,   41,
        0,    0,    0,   41,   41,    0,   41,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   41,   44,    0,    0,
        0,   44,   44,    0,   44,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   44,   47,    0,   47,    0,   47,
        0,   47,    0,    0,    0,   47,   47,    0,   47,    0,

        0,    0,    0,    0,    0,    0,    0,    0,   47,   49,
        0,   49,    0,   49,    0,    0,    0,    0,    0,    0,
       49,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   49,   52,    0,   52,    0,    0,    0,   52,
        0,   52,    0,   52,   52,    0,   52,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   52,   54,    0,   54,
        0,    0,    0,    0,    0,   54,    0,    0,   54,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       54,   56,    0,   56,    0,    0,    0,   56,    0,   56,
        0,   56,   56,    0,   56,    0,    0,    0,    0,    0,

        0,    0,    0,    0,   56,   59,    0,   59,    0,    0,
        0,    0,    0,    0,   59,    0,   59,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   59,   63,    0,    0,
        0,    0,    0,   63,    0,    0,    0,   63,   63,    0,
       63,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       63,   63,   65,    0,    0,    0,    0,   65,   65,    0,
        0,    0,   65,   65,    0,   65,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   65,   69,    0,   69,    0,
        0,    0,   69,    0,    0,    0,   69,   69,    0,   69,
        0,   69,    0,    0,    0,    0,    0,    0,    0,   69,

       70,    0,   70,    0,    0,    0,    0,    0,    0,    0,
        0,   70,    0,    0,    0,   70,    0,    0,    0,    0,
        0,    0,    0,   70,   75,    0,    0,    0,   75,   75,
        0,   75,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   75,   82,    0,   82,    0,    0,    0,    0,    0,
       82,    0,    0,   82,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   82,   83,    0,   83,    0,
        0,    0,   83,    0,   83,    0,   83,   83,    0,   83,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   83,
       84,    0,   84,    0,    0,    0,    0,    0,   84,    0,

        0,   84,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   84,   89,    0,    0,    0,    0,   89,
       89,    0,    0,    0,   89,   89,    0,   89,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   89,   93,    0,
        0,    0,    0,    0,   93,    0,    0,    0,   93,   93,
        0,   93,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   93,   93,   97,    0,    0,    0,    0,   97,   97,
        0,    0,    0,   97,   97,    0,   97,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   97,  103,    0,    0,
        0,    0,  103,  103,    0,    0,    0,  103,  103,    0,

      103,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      103,  107,    0,  107,    0,    0,    0,    0,    0,  107,
        0,    0,  107,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  107,  110,    0,    0,    0,    0,
      110,    0,    0,    0,    0,    0,  110,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  110,  110,  118,
        0,    0,    0,    0,  118,  118,    0,    0,    0,  118,
      118,    0,  118,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  118,  118,  121,    0,    0,    0,    0,  121,
        0,    0,    0,    0,    0,  121,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,  121,  121,  122,
        0,    0,    0,    0,  122,    0,    0,    0,    0,    0,
      122,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  122,  122,  124,    0,    0,    0,    0,  124,  124,
        0,    0,    0,  124,  124,    0,  124,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  124,  124,  125,    0,
        0,    0,    0,  125,  125,    0,    0,    0,  125,  125,
        0,  125,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  125,  125,  128,    0,    0,    0,    0,  128,    0,
        0,    0,    0,    0,  128,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,  128,  128,  129,    0,
        0,    0,    0,  129,  129,    0,    0,    0,  129,  129,
        0,  129,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  129,  129,  136,    0,    0,    0,    0,  136,    0,
        0,    0,    0,    0,  136,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  136,  136,  140,    0,
        0,    0,    0,  140,    0,    0,    0,    0,    0,  140,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  140,  140,  157,    0,    0,    0,  157,  158,  158,
        0,  158,  158,  158,  159,    0,    0,    0,  159,  160,

        0,    0,    0,  160,  160,  161,  161,    0,  161,  161,
      161,  162,    0,    0,    0,  162,  162,  163,  163,    0,
      163,  163,  163,  164,  164,    0,  164,  164,  164,  165,
      165,    0,  165,  165,  165,  166,  166,    0,  166,  166,
      166,  167,    0,    0,    0,  167,  167,  168,    0,    0,
        0,  168,  168,  169,  169,    0,  169,  169,  169,  170,
      170,    0,  170,  170,  170,  171,  171,    0,  171,  171,
      171,  172,    0,    0,    0,  172,  172,  173,    0,    0,
        0,  173,  173,  174,    0,    0,    0,  174,  174,  175,
      175,    0,  175,  175,  175,  176,  176,    0,  176,  176,

      176,  177,  177,    0,  177,  177,  177,  178,  178,    0,
      178,  178,  178,  179,  179,    0,  179,  179,  179,  180,
      180,    0,    0,  180,  180,  181,  181,    0,    0,  181,
      181,  182,  182,    0,    0,  182,  182,  183,  183,    0,
        0,  183,  183,  184,  184,    0,  184,  184,  184,  185,
      185,    0,  185,  185,  185,  186,    0,    0,    0,  186,
      186,  187,    0,    0,    0,  187,  187,  188,  188,    0,
      188,  188,  188,  189,  189,    0,  189,  189,  189,  190,
      190,    0,    0,  190,  190,  191,  191,    0,    0,  191,
      191,  192,  192,    0,    0,  192,  192,  193,  193,    0,

        0,  193,  193,  194,  194,    0,    0,  194,  194,  195,
      195,    0,    0,  195,  195,  196,  196,    0,    0,  196,
      196,  197,  197,    0,    0,  197,  197,  198,  198,    0,
        0,  198,  198,  199,  199,    0,    0,  199,  199,  200,
      200,    0,    0,  200,  200,  201,  201,    0,    0,  201,
      201,  202,  202,    0,    0,  202,  202,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[23] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "shell.l"
/*
 * CS252: Shell project
 *
 * Template file.
 * You will need to add more code here to execute the command table.
 *
 * NOTE: You are responsible for fixing any bugs this code may have!
 *
 * DO NOT PUT THIS PROJECT IN A PUBLIC REPOSITORY LIKE GIT. IF YOU WANT
 * TO MAKE IT PUBLICALLY AVAILABLE YOU NEED TO REMOVE ANY SKELETON CODE
 * AND REWRITE YOUR PROJECT SO IT IMPLEMENTS FUNCTIONALITY DIFFERENT THAN
 * WHAT IS SPECIFIED IN THE HANDOUT. WE OFTEN REUSE PART OF THE PROJECTS FROM
 * SEMESTER TO SEMESTER AND PUTTING YOUR CODE IN A PUBLIC REPOSITORY
 * MAY FACILITATE ACADEMIC DISHONESTY.
 */
/*
 *
 * CS-252 
 * shell.l: lexical analyzer for shell
 * You have to extend it.
 *
 */
#line 26 "shell.l"

#include <string.h>
#include <cstring>
#include "y.tab.hh"
#include <sys/wait.h>
#include <unistd.h>
#include <vector>
#include <stdio.h>
#include <fstream>
#include "shell.hh"

static  void yyunput (int c,char *buf_ptr  );

void myunputc(int c) {
  unput(c);
}


extern "C" char * read_line();

int mygetc(FILE * f) {
  static char *p;
  char ch;

  if (!isatty(0)) {
    return getc(f);
  }

  if (p == NULL || *p == 0) {
    char *s = read_line();
    p = s;
  }

  ch = *p;
  p++;

  return ch;
}

#undef getc
#define getc(f) mygetc(f)


#line 903 "lex.yy.cc"
#line 904 "lex.yy.cc"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 73 "shell.l"


#line 1124 "lex.yy.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 157 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1358 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 75 "shell.l"
{
  return NEWLINE;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 79 "shell.l"
{
  /* Discard spaces and tabs */
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 83 "shell.l"
{
  return GREAT;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 87 "shell.l"
{
  return LESS;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 91 "shell.l"
{
  return PIPE;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 95 "shell.l"
{
  return AMPERSAND;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 99 "shell.l"
{
  return TWOGREAT;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 103 "shell.l"
{
  return GREATGREAT;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 107 "shell.l"
{
  return GREATAMPERSAND;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 111 "shell.l"
{
  return GREATGREATAMPERSAND;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 115 "shell.l"
{
  // Quotes
  std::string str = std::string(yytext);
  str = str.substr(1, str.size() - 2);
  yylval.cpp_string = new std::string(str);;
  return WORD;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 123 "shell.l"
{
  // Subshell
  std::string string =  yytext;
  // Extracting the string b/w $(...) or `...`
  if (string.at(0) == '$')
    string = string.substr(2, string.size() - 3);
  else
    string = string.substr(1, string.size() - 2); 

  // setup input and output
  int tempin;
  int tempout;
  tempin = dup(0);
  tempout = dup(1);

  // Parent creates 2 pipes
  int pin[2];
  int pout[2];
  pipe(pin);
  pipe(pout);

  // Parent writes to pin[1]
  write(pin[1], string.c_str(), string.size());
  write(pin[1], "\n", 1);
  write(pin[1], "exit", 4);
  write(pin[1], "\n", 1);
  close(pin[1]);

  // Child redirect from pin[0] and redirect output to pout[1]
  // Child process runs subshell command and writes output to pout[1]
  dup2(pin[0], 0);
  dup2(pout[1], 1);
  close(pin[0]);
  close(pout[1]);

  // Create child process
  int ret = fork();
  if (ret == 0) {
    // Child process
    char ** args = new char* [2];
    args[0] = (char*) "/proc/self/exe";
    args[1] = NULL;
    execvp(args[0], args);
    perror("execvp for subshell");
    exit(1);
  }
  else if (ret < 0) {
    // error in fork
    perror("fork");
    exit(1);
  }
  else {
    //waitpid(ret, NULL, 0);

    dup2(tempin, 0);
    dup2(tempout, 1);
    close(tempin);
    close(tempout);

    // Read the output from the subshell
    char c;
    char * buffer = (char *) malloc (4000);
    int i = 0;

    // Parent closes pout[1], reads the output from pout[0] 
    // and writes into buffer
    while(read(pout[0], &c, 1)) {
      // Read result into buffer
      if (c == '\n')
        buffer[i++] = ' ';
      else
        buffer[i++] = c;
    }
    close(pout[0]);

    // Terminate
    buffer[i - 1] = '\0';

    // Parents puts chars in the buffer back into lex, in reverse order
    int j = 0;
    for (j = strlen(buffer); j >= 0; j--) {
      myunputc(buffer[j]);
    }
  }
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 209 "shell.l"
{
  std::string *str = new std::string(yytext + strlen("source "));
  std::ifstream fp;
  fp.open(*str);
  std::vector<std::string> lines;
  std::string line;

  while(std::getline(fp, line)) {
    line += "\n";
    lines.push_back(line);
  }
  fp.close();
  int index = lines.size() - 1;
  for(; index >= 0; index--) {
    for (int j = lines[index].length() - 1; j >= 0; j--)
      myunputc(lines[index][j]);
  }
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 230 "shell.l"
{
  // Escaping
  int i = 0;
  char *escape = (char *) malloc(100);
  char *string = yytext;

  while(*string) {
    // Evaluating everthing after "\"
    if (*string == '\\') {
      if (*(string + 1) != '\\') {
        escape[i++] = *(++string);
      }
      else {
        string = string + 1;
        escape[i++] = '\\';
      }
    }
    else {
      escape[i++] = *string;
    }
    string++;
  }
  // Null pointer
  escape[i] = '\0';
  yylval.cpp_string = new std::string(escape);
  return WORD;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 259 "shell.l"
{
  std::string str = yytext;
  std::string target = "";
  std::size_t found_dollar = str.find('$');
  while(found_dollar != -1) {
    std::string var;
    target = target + str.substr(0, found_dollar);
    if (str[found_dollar + 1] == '{') {
      std::size_t end = str.find('}');
      if (end != -1) {
        var = str.substr(found_dollar + 2, end - found_dollar - 2);
        int pid = getpid();
        std::string s = std::to_string(pid);
        target = target + s;
        str = str.substr(end + 1, -1);
      }
    }
    found_dollar = str.find('$');
  }
  target = target + str;
  yylval.cpp_string = new std::string(target);
  return WORD;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 284 "shell.l"
{
  std::string str = yytext;
  std::string target = "";
  std::size_t found_dollar = str.find('$');
  while(found_dollar != -1) {
    std::string var;
    target = target + str.substr(0, found_dollar);
    if (str[found_dollar + 1] == '{') {
      std::size_t end = str.find('}');
      if (end != -1) {
        var = str.substr(found_dollar + 2, end - found_dollar - 2);
        target += target + std::string(getenv(var.c_str()));
        str = str.substr(end + 1, -1);
      }
    }
    found_dollar = str.find('$');
  }
  target = target + str;
  yylval.cpp_string = new std::string(target);
  return WORD;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 306 "shell.l"
{
  std::string str = yytext;
  std::string target = "";
  std::size_t found_dollar = str.find('$');
  while(found_dollar != -1) {
    std::string var;
    target = target + str.substr(0, found_dollar);
    if (str[found_dollar + 1] == '{') {
      std::size_t end = str.find('}');
      if (end != -1) {
        var = str.substr(found_dollar + 2, end - found_dollar - 2);
        target += target + std::string(getenv(var.c_str()));
        str = str.substr(end + 1, -1);
      }
    }
    found_dollar = str.find('$');
  }
  target = target + str;
  yylval.cpp_string = new std::string(target);
  return WORD;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 328 "shell.l"
{
  std::string str = yytext;
  std::string target = "";
  std::size_t found_dollar = str.find('$');
  while(found_dollar != -1) {
    std::string var;
    target = target + str.substr(0, found_dollar);
    if (str[found_dollar + 1] == '{') {
      std::size_t end = str.find('}');
      if (end != -1) {
        var = str.substr(found_dollar + 2, end - found_dollar - 2);
        std::string var_new = Shell::value_arg;
        target += target + var_new;
        //target += target + std::string(getenv(var.c_str()));
        str = str.substr(end + 1, -1);
      }
    }
    found_dollar = str.find('$');
  }
  target = target + str;
  yylval.cpp_string = new std::string(target);
  return WORD;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 354 "shell.l"
{
  //Environment variable expansion
  std::string str = yytext;
  std::string target = "";
  std::size_t found_dollar = str.find('$');
  while(found_dollar != -1) {
    std::string var;
    target = target + str.substr(0, found_dollar);
    if (str[found_dollar + 1] == '{') {
      std::size_t end = str.find('}');
      if (end != -1) {
        var = str.substr(found_dollar + 2, end - found_dollar - 2);
        /*
        if (var == '$') {
          int pid = getpid();
          std::string s = std::to_string(pid);
          target = target + s;
        }
        */
        if (getenv(var.c_str()))
          target = target + getenv(var.c_str());
        else
          target = target + var;
        str = str.substr(end + 1, -1);
      }
    }
    found_dollar = str.find('$');
  }
  target = target + str;
  yylval.cpp_string = new std::string(target);
  return WORD;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 388 "shell.l"
{
  // Tilde Expansion
  std::string str = yytext;
  std::string home_dir = getenv("HOME");
  int length = str.size();
  if (length != 1) {
    if (str[1] == '/')
      str = home_dir + str.substr(1, -1);
    else
      str = std::string("/homes/") + str.substr(1, -1);
    yylval.cpp_string = new std::string(str);
  }
  else
    yylval.cpp_string = new std::string(home_dir);
  return WORD;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 405 "shell.l"
{
  /* Assume that file names have only alpha chars */
  yylval.cpp_string = new std::string(yytext);
  return WORD;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 410 "shell.l"
ECHO;
	YY_BREAK
#line 1589 "lex.yy.cc"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 157 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 157 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 156);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 410 "shell.l"
